### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by mshaler** [sueszli/notionBackup#7]
(node:31583) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

/Users/mshaler/notionBackup/notionbackup.ts:16
    assert(fs.existsSync(arg))
    ^
AssertionError [ERR_ASSERTION]: false == true
    at getInputPath (~/notionBackup/notionbackup.ts:16:5)
    at main (~/notionBackup/notionbackup.ts:195:23)
    at Object.<anonymous> (~/notionBackup/notionbackup.ts:208:1)
    at Module._compile (node:internal/modules/cjs/loader:1504:14)
    at Module.m._compile (~/notionBackup/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1588:10)
    at Object.require.extensions.<computed> [as .ts] (~/notionBackup/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1282:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1098:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)

**Comment by sueszli** [comment]
the error seems to be from a failed assertion in line 16 - the given filepath doesn't point to an existing zip file.

regarding the deprecation warning: yeah i should bump the versions when i get to it or put everything in a docker container.
